version: '3'

services:
  app:
    # Uncomment the next line to use a non-root user. See https://aka.ms/vscode-remote/containers/non-root-user.
    # user: 1000

    build: 
      context: .

    volumes:
      - ./recipe:/workspace
    ports:
      - "8000:8000"
      - "3000:3000"
      - "5500:5500"
    # Overrides default command so things don't shut down after the process ends.
    command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"
    

