version: '3'

services:
  app:
    # Uncomment the next line to use a non-root user. See https://aka.ms/vscode-remote/containers/non-root-user.
    # user: 1000

    build: 
      context: .

    volumes:
      - ../recipe:/workspace
    ports:
      - "8687:8687"
      - "3000:3000"
      - "5500:5500"
    # Overrides default command so things don't shut down after the process ends.

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db


  db:
    image: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password


