# Generated by Django 2.2.6 on 2019-12-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
