# Generated by Django 2.2.6 on 2019-12-26 08:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191220_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=app.models.recipe_image_file_path),
        ),
    ]
